n = input('Digite algo: ')
print('Qual é o tipo?',type(n))
print('É alphanumerico? ', n.isalnum())
print('É numérico? ', n.isnumeric())
print('É apenas letra?', n.isalpha())
print('É um nome valido? ', n.isidentifier())
print('Só tem letras maiusculas? ', n.isupper())
print('Só tem letras minusculas? ', n.islower())
print('É imprimivel? ', n.isprintable())
print('Possui apenas espaços? ', n.isspace())
print('Esta capitalizada? ', n.istitle())
